export const products = [
  {
    id: 1,
    title: "Single Room",
    description: "A small and neat single bed ",
    price: "500",
    img: "../../Images/Single.jpg",
    quantity: 0,
  },
  {
    id: 2,
    title: "Double Room",
    description: "A double bedroom with all facilities",
    price: "900",
    img: "../../Images/Double.jpg",
    quantity: 0,
  },
  {
    id: 3,
    title: "Queen Room",
    description: "Big and Spacious room ",
    price: "1500",
    img: "../../Images/Queen.jpg",
    quantity: 0,
  },
  {
    id: 4,
    title: "King Room",
    description: "King size room with premium facilities and a Bathtub attached",
    price: "2800",
    img: "../../Images/King.jpg",
    quantity: 0,
  },
  {
    id: 5,
    title: "5Star Suite",
    description: "A Premium View with room service and food charges included",
    price: "4999",
    img: "../../Images/Suite.jpg",
    quantity: 0,
  },
  {
    id: 6,
    title: "Serviced Apartment",
    description: "A monthly charge for 1BHK with food facility included ",
    price: "15000",
    img: "../../Images/Apartment.jpg",
    quantity: 0,
  },
];
